name: Deploy Spring Boot

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Copy jar to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 125.133.62.199
          username: marssq
          key: ${{ secrets.SSH_KEY }}
          port: 26022
          source: "build/libs/*.jar,Dockerfile"
          target: "~/mars-backend"

      - name: Run Docker
        uses: appleboy/ssh-action@v1
        with:
          host: 125.133.62.199
          username: marssq
          key: ${{ secrets.SSH_KEY }}
          port: 26022
          script: |
            cd ~/mars-backend
            docker stop mars7 || true
            docker rm mars7 || true
            docker rmi mars7 || true
            ls -R
            docker build --no-cache -t mars7 .
            docker run -d \
              --name mars7 \
              --network mars \
              -p 26900:8080 \
              --env-file .env \
              --restart always \
              mars7
